# profile config
# 参考地址: https://www.baeldung.com/spring-profiles

server:
  port: 11001


logging:
  config: classpath:log4j2.xml
  level:
    tech.qijin.cell.im.db: DEBUG

spring:
  profiles:
    active: dev
  datasource:
    druid:
      im:
        url: jdbc:mysql://127.0.0.1:3306/cell_im?useUnicode=true&characterEncoding=utf-8
        username: admin
        password: Admin_@123
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 10
        max-active: 30
        min-idle: 5
        max-wait: 60