CREATE TABLE `order_summary` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `former_order_id` bigint(20) unsigned DEFAULT '0' COMMENT '拆单前的原订单ID',
  `order_no` varchar(60) NOT NULL COMMENT '订单号',
  `acct_id` bigint(20) unsigned NOT NULL COMMENT '账号ID',
  `customer_id` bigint(20) unsigned NOT NULL COMMENT '客户ID',
  `customer_name` varchar(255) NOT NULL COMMENT '客户名称',
  `poi_id` bigint(20) unsigned NOT NULL COMMENT '门店ID',
  `poi_name` varchar(255) NOT NULL COMMENT '门店名称',
  `poi_type` tinyint(4) DEFAULT '1' COMMENT '门店类型：1-总店，2-分店',
  `recipient_info_id` bigint(20) unsigned NOT NULL COMMENT '配送（地址）信息ID',
  `remark` varchar(1024) DEFAULT NULL COMMENT '订单备注',
  `cancel_excuse` varchar(1204) DEFAULT NULL COMMENT '取消原因',
  `cancel_remark` varchar(1024) DEFAULT NULL COMMENT '订单取消备注',
  `reject_excuse` varchar(1024) DEFAULT NULL COMMENT '拒单原因（保留）',
  `city_id` int(11) NOT NULL COMMENT '城市ID',
  `status` smallint(10) NOT NULL COMMENT '订单状态：10-待支付，15-未接单，19-接单中，20-已接单，55-已发货，60-已送达，89-取消中，90-已取消',
  `payment_type` tinyint(4) NOT NULL COMMENT '支付类型：1-在线支付',
  `payment_method` tinyint(4) DEFAULT '-1' COMMENT '结款渠道: 1-微信，2-支付宝，3-余额,4-组合支付,5-线下付款',
  `payment_status` tinyint(4) DEFAULT '0' COMMENT '结款状态：0-未结款，1-已结款',
  `paid_time` datetime DEFAULT NULL COMMENT '结款时间',
  `payment_id` int(11) unsigned DEFAULT NULL COMMENT '（在线支付）支付单ID',
  `origin_price` decimal(12,2) DEFAULT '99999.00' COMMENT ' 订单原价总金额',
  `total_price` decimal(12,2) DEFAULT '99999.00' COMMENT '订单（优惠前）销售价总金额',
  `order_price` decimal(12,2) DEFAULT '99999.00' COMMENT '订单（优惠后）实际金额',
  `reduced_amount` decimal(12,2) DEFAULT '0.00' COMMENT '订单优惠金额',
  `order_type` tinyint(4) NOT NULL COMMENT '订单类型:1-自下单，2-换货订单',
  `source` tinyint(4) NOT NULL COMMENT '订单来源：0-未定义，1-WeChat，2-客服代下单',
  `version` smallint(10) DEFAULT '1' COMMENT '订单版本',
  `valid` tinyint(4) DEFAULT '1' COMMENT '是否有效：1-有效，0-无效',
  `creator_id` int(11) unsigned DEFAULT '0' COMMENT '代下单时下单人ID',
  `ctime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `utime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_customer_poi_id` (`customer_id`),
  KEY `idx_poi_id_channel_id` (`poi_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';

